---
title: "MATH2270 Assignment 2"
subtitle: Visualising Open Data
output:
  pdf_document: default
  html_notebook: default
---

## Student Details

* Student Name (s3000000)

```{r}
## Load Libraries
require(ggplot2)
require(dplyr)
require(splitstackshape)
library(googleVis)
require(ggvis)
```

## Data

```{r}
# Load your data and prepare for visualisation
Data2017 = read.csv('data/survey_results_public.csv')

Education = Data2017 %>% select(Respondent,EducationTypes,SelfTaughtTypes,DeveloperType) %>% 
  filter(!is.na(EducationTypes) & !is.na(EducationTypes) & DeveloperType %in% 
           c('Data scientist','Machine learning specialist','Developer with a statistics or mathematics background'))

Education_long <- cSplit(indt = Education, 
                         splitCols = c('EducationTypes','SelfTaughtTypes','DeveloperType'), sep = ";", direction = "long")

x = data.frame(table(Education_long$DeveloperType,Education_long$EducationTypes))
y = data.frame(table(Education_long$EducationTypes,Education_long$SelfTaughtTypes))

defaulter<-rbind(x,y)

```


## Visualisation

```{r}

# Plotting

sk2 <- gvisSankey(defaulter, from='Var1', to='Var2', weight='Freq',
                  options=list(height=400, width=600))
plot(sk2)

```

Data Source
https://insights.stackoverflow.com/survey/


